spring:
  datasource:
    username: root
    password: mxf0222#ABC
    url: jdbc:mysql://localhost:3306/creditRisk
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
  address: 127.0.0.1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


